sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: yarn
script:
  - kcd-scripts validate lint,build,test:cover
after_success: kcd-scripts travis-after-success
branches:
  only: master
