language: node_js
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: 8
install:
  - yarn --frozen-lockfile
script:
  - kcd-scripts validate lint,build,test:cover
after_success: kcd-scripts travis-after-success
branches:
  only: master
