sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
script:
  - kcd-scripts validate lint,test:cover
branches:
  only: master
