sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
before_script:
  - cd stories
  - npm install
  - cd ..
script:
  - kcd-scripts validate lint,test:cover
after_success: kcd-scripts travis-after-success
branches:
  only: master
