language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js: 10
install:
  - yarn --frozen-lockfile
script:
  - yarn lint
  - yarn build
  - yarn test --coverage
after_success: yarn semantic-release
branches:
  only: master
